# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asterisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='numbers',
            options={},
        ),
    ]
