# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-09 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asterisk', '0002_auto_20160209_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField()),
                ('added_timestamp', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_comment',
            },
        ),
        migrations.AddField(
            model_name='cdr',
            name='number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='asterisk.Numbers'),
        ),
    ]
